### ISSUE TITLE
error 500 (api/client/info)

### ISSUE THREAD

**Issue by vetal20600** [gamecredits-project/block-exploder#17]
I am trying to get rid of error 500 which is rises on api/client/info. Have no clue what is the reason. Maybe you can help guys? 
![screen shot 2017-12-22 at 21 56 43](https://user-images.githubusercontent.com/4103746/34311015-5d181b22-e763-11e7-8a12-d008f28c6766.png)

**Comment by MicicFilip** [comment]
Hello @vetal20600 , can you show me the full log of that error.

**Comment by vetal20600** [comment]
@MicicFilip there is exploder-api.log:
```
......
    return ClientInfoSerializer.to_web(client_info)
  File "/usr/local/lib/python2.7/dist-packages/exploder-0.0.1-py2.7.egg/exploder_api/serializers.py", line 96, in to_web
    "ip": client_info["ip"],
KeyError: 'ip'
ERROR:tornado.access:500 GET /api/client/info (127.0.0.1) 3.59ms
[2017-12-25 15:08:24,925] ERROR in app: Exception on /api/client/info [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.12.2-py2.7.egg/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.12.2-py2.7.egg/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/Flask_Cors-3.0.3-py2.7.egg/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.12.2-py2.7.egg/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.12.2-py2.7.egg/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.12.2-py2.7.egg/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/connexion-1.2-py2.7.egg/connexion/decorators/decorator.py", line 66, in wrapper
    response = function(request)
  File "/usr/local/lib/python2.7/dist-packages/connexion-1.2-py2.7.egg/connexion/decorators/decorator.py", line 42, in wrapper
    response = function(request)
  File "/usr/local/lib/python2.7/dist-packages/connexion-1.2-py2.7.egg/connexion/decorators/parameter.py", line 219, in wrapper
    return function(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/exploder-0.0.1-py2.7.egg/exploder_api/api.py", line 356, in get_client_info
    return ClientInfoSerializer.to_web(client_info)
  File "/usr/local/lib/python2.7/dist-packages/exploder-0.0.1-py2.7.egg/exploder_api/serializers.py", line 96, in to_web
    "ip": client_info["ip"],
KeyError: 'ip'
ERROR:tornado.access:500 GET /api/client/info (127.0.0.1) 3.62ms
```

**Comment by MicicFilip** [comment]
@vetal20600 it seems that celery didn't write the IP of the node that block explorer takes information from. Just restart all supervisor processes and you are good to go.

**Comment by vetal20600** [comment]
@MicicFilip is it enough to restart to put in terminal `sudo ansible-playbook env/configure-vagrant.yml`?

**Comment by MicicFilip** [comment]
@vetal20600 no, just run `sudo supervisorctl restart all`

**Comment by vetal20600** [comment]
@MicicFilip stil the same.
restart log:
```
socket: stopped
redis: stopped
celery: stopped
exploder-api1: stopped
exploder-api2: stopped
mongod: ERROR (abnormal termination)
socket: ERROR (abnormal termination)
redis: started
celery: started
exploder-api1: started
exploder-api2: started
```

same log for exploder:
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.12.2-py2.7.egg/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.12.2-py2.7.egg/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/Flask_Cors-3.0.3-py2.7.egg/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.12.2-py2.7.egg/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.12.2-py2.7.egg/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.12.2-py2.7.egg/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/connexion-1.2-py2.7.egg/connexion/decorators/decorator.py", line 66, in wrapper
    response = function(request)
  File "/usr/local/lib/python2.7/dist-packages/connexion-1.2-py2.7.egg/connexion/decorators/decorator.py", line 42, in wrapper
    response = function(request)
  File "/usr/local/lib/python2.7/dist-packages/connexion-1.2-py2.7.egg/connexion/decorators/parameter.py", line 219, in wrapper
    return function(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/exploder-0.0.1-py2.7.egg/exploder_api/api.py", line 356, in get_client_info
    return ClientInfoSerializer.to_web(client_info)
  File "/usr/local/lib/python2.7/dist-packages/exploder-0.0.1-py2.7.egg/exploder_api/serializers.py", line 96, in to_web
    "ip": client_info["ip"],
KeyError: 'ip'
ERROR:tornado.access:500 GET /api/client/info (127.0.0.1) 1.75ms
```

socket log error:
```
Traceback (most recent call last):
  File "/home/greglabone/_gbe/block-exploder/socket/app.py", line 4, in <module>
    import socket_transmitter as st
  File "/home/greglabone/_gbe/block-exploder/socket/socket_transmitter.py", line 5, in <module>
    iv.CURRENT_BLOCK = helpp.get_latest_five_blocks()[-1]['height']
  File "/home/greglabone/_gbe/block-exploder/socket/helpers.py", line 8, in get_latest_five_blocks
    five_blocks = res.json()
  File "/usr/local/lib/python2.7/dist-packages/requests-2.18.4-py2.7.egg/requests/models.py", line 892, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/simplejson-3.13.2-py2.7-linux-x86_64.egg/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python2.7/dist-packages/simplejson-3.13.2-py2.7-linux-x86_64.egg/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python2.7/dist-packages/simplejson-3.13.2-py2.7-linux-x86_64.egg/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/home/greglabone/_gbe/block-exploder/socket/app.py", line 4, in <module>
    import socket_transmitter as st
  File "/home/greglabone/_gbe/block-exploder/socket/socket_transmitter.py", line 5, in <module>
    iv.CURRENT_BLOCK = helpp.get_latest_five_blocks()[-1]['height']
  File "/home/greglabone/_gbe/block-exploder/socket/helpers.py", line 8, in get_latest_five_blocks
    five_blocks = res.json()
  File "/usr/local/lib/python2.7/dist-packages/requests-2.18.4-py2.7.egg/requests/models.py", line 892, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/simplejson-3.13.2-py2.7-linux-x86_64.egg/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python2.7/dist-packages/simplejson-3.13.2-py2.7-linux-x86_64.egg/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python2.7/dist-packages/simplejson-3.13.2-py2.7-linux-x86_64.egg/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by MicicFilip** [comment]
@vetal20600 Is mongo running as expected?

**Comment by MicicFilip** [comment]
@vetal20600 Is mongo running as expected?

**Comment by vetal20600** [comment]
yes, I can enter to database and check records. There is no such field for some reason

**Comment by MicicFilip** [comment]
@vetal20600 Destroy the vagrant machine and run ansible-playbook command on a clean one

**Comment by vetal20600** [comment]
I had issues with running virtual machine, no vagrant instance running

**Comment by MicicFilip** [comment]
@vetal20600 you have to run Vagrant for everything to work, that is part of the stack. Run Vagrant and everything will work as intended. Good luck!
